"""empty message

Revision ID: 0edeaf97b487
Revises: 143b7e6cb64b
Create Date: 2017-09-04 18:39:27.756647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0edeaf97b487'
down_revision = '143b7e6cb64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aws_instance_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('instance_type', sa.String(length=120), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aws_instance_id')
    )
    op.create_index(op.f('ix_instance_project_id'), 'instance', ['project_id'], unique=False)
    op.create_table('volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aws_volume_id', sa.String(length=120), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('volume_type', sa.String(length=120), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aws_volume_id')
    )
    op.create_index(op.f('ix_volume_project_id'), 'volume', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volume_project_id'), table_name='volume')
    op.drop_table('volume')
    op.drop_index(op.f('ix_instance_project_id'), table_name='instance')
    op.drop_table('instance')
    # ### end Alembic commands ###
