"""empty message

Revision ID: 8f60e2552f8d
Revises: 0edeaf97b487
Create Date: 2017-09-04 18:59:53.342122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f60e2552f8d'
down_revision = '0edeaf97b487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('role', sa.Integer(), nullable=False))
    op.drop_column('volume', 'volume_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volume', sa.Column('volume_type', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('instance', 'role')
    # ### end Alembic commands ###
