"""empty message

Revision ID: b8db3411474d
Revises: bdf701bb7d4b
Create Date: 2017-09-07 16:37:48.834985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8db3411474d'
down_revision = 'bdf701bb7d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apscheduler_jobs')
    op.alter_column('config', 'dataset_loc',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)
    op.alter_column('config', 'model_path',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)
    op.alter_column('config', 'predict',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('config', 'predict',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('config', 'model_path',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
    op.alter_column('config', 'dataset_loc',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    # ### end Alembic commands ###
