"""empty message

Revision ID: bdf701bb7d4b
Revises: e42b2ed3b865
Create Date: 2017-09-07 16:36:26.519552

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bdf701bb7d4b'
down_revision = 'e42b2ed3b865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_loc', sa.String(length=240), nullable=True),
    sa.Column('update_with', sa.String(length=120), nullable=True),
    sa.Column('retrain_after', sa.Integer(), nullable=True),
    sa.Column('model_path', sa.String(length=240), nullable=True),
    sa.Column('train', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('test', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('predict', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_project_id'), 'config', ['project_id'], unique=False)
    op.drop_table('apscheduler_jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'apscheduler_jobs_pkey')
    )
    op.drop_index(op.f('ix_config_project_id'), table_name='config')
    op.drop_table('config')
    # ### end Alembic commands ###
